const params = "?fontsize=22&module=%2Findex.html";
const embed = "https://codesandbox.io/embed/";
export const VUE_FUNCTION_IMG_SRC = "https://i.imgur.com/Cz1axKY.png";
export const LIFECYCLE_1_IMG_SRC = "https://i.imgur.com/oUOKS4S.png";
export const LIFECYCLE_2_IMG_SRC = "https://i.imgur.com/Z7u2PwG.png";
export const LIFECYCLE_3_IMG_SRC = "https://i.imgur.com/bSjpHOy.png";
export const DYNAMIC_CLASS_IMG_SRC = "https://i.imgur.com/kIcm5ef.png";
export const DYNAMIC_STYLE_IMG_SRC = "https://i.imgur.com/zcdZu8J.png";
export const DYNAMIC_INLINE_STYLE_IMG_SRC = "https://i.imgur.com/E58vF9R.png";
export const ES6_INLINE_STYLE_IMG_SRC = "https://i.imgur.com/JwNnAZe.png";
export const V_IF_IMG_SRC = "https://i.imgur.com/aediBJS.png";
export const V_IF_TEMPLATE_IMG_SRC = "https://i.imgur.com/vMcOYKL.png";
export const V_ELSE_TEMPLATE_IMG_SRC = "https://i.imgur.com/3uvSr8z.png";
export const V_ELSE_IF_TEMPLATE_IMG_SRC = "https://i.imgur.com/NGTA0Qz.png";
export const V_SHOW_IMG_SRC = "https://i.imgur.com/LfIKfIr.png";
export const V_FOR_IMG_SRC = "https://i.imgur.com/dJWvGsS.png";
export const V_FOR_OBJ_IMG_SRC = "https://i.imgur.com/1pM5PmT.png";
export const CLICK_HTML_IMG_SRC = "https://i.imgur.com/nL6eeC0.png";
export const CLICK_METHOD_IMG_SRC = "https://i.imgur.com/9dnDHWQ.png";
export const EVENT_MOD_IMG_SRC = "https://i.imgur.com/Kq0YC4m.png";
export const BINDING_IMG_SRC = "https://i.imgur.com/tdMpqti.png";
export const COMPONENTS_BASIC_IMG_SRC = "https://i.imgur.com/zaQDOQJ.png";
export const FIRST_COMPONENT_IMG_SRC = "https://i.imgur.com/NihrMSi.png";

export const FIRST_VUE_IFRAME_SRC = `${embed}4lr49kn1vw${params}`;
export const COMPUTED_VUE_IFRAME_SRC = `${embed}6y2pjmqkm3${params}`;
export const METHODS_VUE_IFRAME_SRC = `${embed}kworn00xxo${params}`;
export const COMPUTED_VS_METHODS_VUE_IFRAME_SRC = `${embed}0xqj5wjv2n${params}`;
export const LIFECYCLE_HOOKS_IFRAME_SRC = `${embed}9q33vx8oow${params}`;
export const INTERPOLATIONS_IFRAME_SRC = `${embed}qv8q6x8x7j${params}`;
export const OBJECT_CLASS_BINDING_IFRAME_SRC = `${embed}43890v97y9?fontsize=17&module=%2Findex.html`;
export const COMPUTED_CLASS_BINDING_IFRAME_SRC = `${embed}ql5zkjl4z9?fontsize=17&module=%2Findex.html`;
export const ARRAY_CLASS_BINDING_IFRAME_SRC = `${embed}wkry5l11p8?fontsize=17&module=%2Findex.html`;
export const INLINE_STYLE_BINDING_IFRAME_SRC = `${embed}912p60571y?fontsize=16&module=%2Findex.html`;
export const DATA_STYLE_BINDING_IFRAME_SRC = `${embed}qkm85z1wvq${params}`;
export const VIF_IFRAME_SRC = `${embed}v8y3qly53y${params}`;
export const VIF_TEMPLATE_IFRAME_SRC = `${embed}m77q8066x8?fontsize=16&module=%2Findex.html`;
export const VELSE_TEMPLATE_IFRAME_SRC = `${embed}k516mx8o5?fontsize=16&module=%2Findex.html`;
export const VELSEIF_TEMPLATE_IFRAME_SRC = `${embed}y2jnwv529v?fontsize=16&module=%2Findex.html`;
export const VFOR_IFRAME_SRC = `${embed}k5vplyp70r?fontsize=17&module=%2Findex.html`;
export const VFOR_OBJ_IFRAME_SRC = `${embed}jn749zw2lw?fontsize=15&module=%2Findex.html`;
export const VFOR_KEY_OBJ_IFRAME_SRC = `${embed}py11l64kk0?fontsize=15&module=%2Findex.html`;
export const VFOR_COMPUTED_OBJ_IFRAME_SRC = `${embed}9316rkn41y?fontsize=17&module=%2Findex.html`;
export const CLICK_IFRAME_SRC = `${embed}q80m9zq3j?fontsize=17&module=%2Findex.html`;
export const CLICK_HANDLER_IFRAME_SRC = `${embed}9ornym9kmw?fontsize=17&module=%2Findex.html`;
export const CLICK_INLINE_HANDLER_IFRAME_SRC = `${embed}jl3xqlyyx5?fontsize=17&module=%2Findex.html`;
export const EVENT_MOD_IFRAME_SRC = `${embed}v8v9r73nj5?view=editor&fontsize=17&module=%2Findex.html`;
export const KEY_MODS_IFRAME_SRC = `${embed}zxzkokjjy4?fontsize=19&module=%2Findex.html`;
export const DATABIND_IFRAME_SRC = `${embed}6y6k98lvvr?fontsize=14&module=%2Findex.html`;
export const DATABIND2_IFRAME_SRC = `${embed}p78wm80vvq?fontsize=14&module=%2Findex.html`;
export const SIMPLE_COMPONENT_IFRAME_SRC = `${embed}nr7z34345j?fontsize=18&module=%2Findex.html`;

export const IFRAME_STYLE =
  "width:100%; height:550px; border:0; border-radius: 4px; overflow:hidden;";
export const IFRAME_SANDBOX =
  "allow-modals allow-forms allow-popups allow-scripts allow-same-origin";
